### ISSUE TITLE
Continue to train

### ISSUE THREAD

**Issue by zhaojianghe16** [MaybeShewill-CV/attentive-gan-derainnet#11]
你好，我想继续train你的model，因为觉得很强大。有些疑问希望能得到解答~
     如果是用不同于原作者的dataset进行training（新的dataset，都是新的image pairs）， 那这个对network的影响是什么呢？我是想用更广泛的图片training然后训练出来的再叠加到原来trained model上面取得更广泛的应用性。请问应该怎么样安排dataset呢？请问我是应该将我新的images pairs和原来的dataset混在一起再继续跑吗？还是说有什么关于不同类型分开training最后可以通过某一个方法合并weights的方法呢？
     谢谢你：）

**Comment by MaybeShewill-CV** [comment]
@zhaojianghe16 你可以fintuning原作者提供数据集训练出来的模型，也可以直接使用你的心数据集进行训练，新数据集训练可能需要调整一些超参数。

**Comment by gaochubushenghan** [comment]
请教一下为什么会出现下边的问题
Traceback (most recent call last):
  File "tools/test_model.py", line 22, in <module>
    from attentive_gan_model import derain_drop_net
ImportError: No module named attentive_gan_model

**Comment by MaybeShewill-CV** [comment]
@gaochubushenghan PYTHONPATH设置不对 需要把这个工程的根目录添加近PYTHONPATH中

**Comment by Jay-Jia** [comment]
@MaybeShewill-CV  Can you provide your email address? I have some related questions and want to talk privately.

**Comment by MaybeShewill-CV** [comment]
@Jay-Jia OK howard327@163.com
