### ISSUE TITLE
BN problem

### ISSUE THREAD

**Issue by RobinCSIRO** [MaybeShewill-CV/attentive-gan-derainnet#12]
Thanks for the implementation! 
Question: The batch_size has been assigned as 1, why batch normalization is still used? Functioned the same as instance normalization?

**Comment by MaybeShewill-CV** [comment]
@RobinCSIRO Thanks for ask such a good question. I have not noticed that before. I will figure out it later:)

**Comment by MaybeShewill-CV** [comment]
@RobinCSIRO You may check the new readme file to discuss the problem and I have uploaded a new model there you may test it:)

**Comment by RobinCSIRO** [comment]
> @RobinCSIRO You may check the new readme file to discuss the problem and I have uploaded a new model there you may test it:)

Thanks :+1:

**Comment by MaybeShewill-CV** [comment]
@RobinCSIRO You may test use GN to replace origin BN layer. I will update the code and upload a new model with GN layer:)
