### ISSUE TITLE
关于训练

### ISSUE THREAD

**Issue by gaochubushenghan** [MaybeShewill-CV/attentive-gan-derainnet#16]
File "tools/train_model.py", line 217, in <module>
    train_model(args.dataset_dir, weights_path=args.weights_path)
  File "tools/train_model.py", line 175, in train_model
    gt_imgs, label_imgs, mask_imgs = train_dataset.next_batch(CFG.TRAIN.BATCH_SIZE)
  File "/home/hp/文档/gitcode/attentive-gan-derainnet-master/tools/data_provider/data_provider.py", line 144, in next_batch
    gt_image = cv2.resize(gt_image, (CFG.TRAIN.IMG_WIDTH, CFG.TRAIN.IMG_HEIGHT))
cv2.error: OpenCV(3.4.3) /io/opencv/modules/imgproc/src/resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

请问在训练时为什么会出现这种错误？非常感谢

**Comment by MaybeShewill-CV** [comment]
@gaochubushenghan 应该是图像路径你写错了 检查一下:)

**Comment by gaochubushenghan** [comment]
检查了一下路径也没问题，我就是直接在training_data_example这个文件夹里边改的样本和.txt文件，但是样本的数目比较少

**Comment by MaybeShewill-CV** [comment]
@gaochubushenghan 截图你的txt文件

**Comment by gaochubushenghan** [comment]
我就稍微找了几个样本，试一下能不能把代码跑通
------------------ 原始邮件 ------------------
发件人: "MaybeShewill-CV"<notifications@github.com>;
发送时间: 2018年11月12日(星期一) 下午5:44
收件人: "MaybeShewill-CV/attentive-gan-derainnet"<attentive-gan-derainnet@noreply.github.com>;
抄送: "王晓阳"<546574489@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [MaybeShewill-CV/attentive-gan-derainnet] 关于训练 (#16)




@gaochubushenghan 截图你的txt文件

**Comment by MaybeShewill-CV** [comment]
@gaochubushenghan 请截图你的txt文件

**Comment by gaochubushenghan** [comment]
![image](https://user-images.githubusercontent.com/40535692/48345403-e8da7c00-e6b2-11e8-969d-f875e229e8c8.png)

**Comment by gaochubushenghan** [comment]
![image](https://user-images.githubusercontent.com/40535692/48345479-18898400-e6b3-11e8-84cb-d84486f94375.png)

**Comment by MaybeShewill-CV** [comment]
@gaochubushenghan 由于你使用相对路径很有可能图像没有正常读入 如果你不能自己确定图像是不是正确读入 最简单的方法就是把相对路径改成绝对路径:)

**Comment by gaochubushenghan** [comment]
能不能说一下怎么改呢？不太清楚这一块。非常感谢

**Comment by MaybeShewill-CV** [comment]
@gaochubushenghan 就是把txt文件里面的文件路径从相对路径改写成绝对路径就可以了==!

**Comment by gaochubushenghan** [comment]
是要改成这样吗？还是报一样的错

**Comment by gaochubushenghan** [comment]
![image](https://user-images.githubusercontent.com/40535692/48348212-9fdaf580-e6bb-11e8-88f3-519ecfc390eb.png)

**Comment by MaybeShewill-CV** [comment]
@gaochubushenghan 那你可以调试进入那个函数 看图像是不是正常读入了

**Comment by gaochubushenghan** [comment]
好的  我再研究一下  非常感谢您的解答

**Comment by MaybeShewill-CV** [comment]
@gaochubushenghan 刚测试过 绝对路径没有这个问题 你可以再看看你哪里弄错了:)

**Comment by gaochubushenghan** [comment]
能让我看一下你的绝对路径下的TXT文件吗






------------------ 原始邮件 ------------------
发件人: "MaybeShewill-CV"<notifications@github.com>;
发送时间: 2018年11月12日(星期一) 晚上8:54
收件人: "MaybeShewill-CV/attentive-gan-derainnet"<attentive-gan-derainnet@noreply.github.com>;
抄送: "王晓阳"<546574489@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [MaybeShewill-CV/attentive-gan-derainnet] 关于训练 (#16)




@gaochubushenghan 刚测试过 绝对路径没有这个问题 你可以再看看你哪里弄错了:)

**Comment by MaybeShewill-CV** [comment]
@gaochubushenghan 这个不方便 你自己调试下就可以了 你这个问题就是图像没正确读入:)

**Comment by gaochubushenghan** [comment]
好的  非常感谢


------------------ 原始邮件 ------------------
发件人: "MaybeShewill-CV"<notifications@github.com>;
发送时间: 2018年11月12日(星期一) 晚上8:57
收件人: "MaybeShewill-CV/attentive-gan-derainnet"<attentive-gan-derainnet@noreply.github.com>;
抄送: "王晓阳"<546574489@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [MaybeShewill-CV/attentive-gan-derainnet] 关于训练 (#16)




@gaochubushenghan 这个不方便 你自己调试下就可以了 你这个问题就是图像没正确读入:)
