### ISSUE TITLE
What would be the recommended configuration of training on Tesla P4 GPU

### ISSUE THREAD

**Issue by zhaojianghe16** [MaybeShewill-CV/attentive-gan-derainnet#17]
Dear Friend,
     Thank you for your code. I am going to train the network from scratch on **Tesla P4**.  Could you please give any suggestion about the **global configuration**?  I keep getting a warning of exceeding system's memory. Does this increase the time for training?  

My Global configuration is as follows:
I1120 16:16:41.641378 23545 train_model.py:135] Global configuration is as follows:
I1120 16:16:41.641667 23545 train_model.py:136] {'TRAIN': {'**IMG_HEIGHT': 480, 'BATCH_SIZE': 1, 'LEARNING_RATE': 0.002, 'IMG_WIDTH                    ': 360, 'GPU_MEMORY_FRACTION': 1, 'EPOCHS': 200010, 'TF_ALLOW_GROWTH': True**}, 'TEST': {'IMG_WIDTH': 360, 'IMG_HEIGHT': 480, 'BATC                    H_SIZE': 1, 'GPU_MEMORY_FRACTION': 1, 'TF_ALLOW_GROWTH': True}}
I1120 16:16:45.810997 23545 train_model.py:144] Training from scratch
  
      2018-11-20 16:17:30.196406: W tensorflow/core/framework/allocator.cc:108] **Allocation of 2211840000 exceeds 10% of system memory.**

     Thank you so much:)

My Best,
Zhao

**Comment by MaybeShewill-CV** [comment]
@zhaojianghe16 First make sure your GPU works normally. If your gpu works normally then you may adjust the batch size as large as possible in my opinion:)
