### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by huoguangdiandian** [MaybeShewill-CV/attentive-gan-derainnet#18]
问一个关于数据集的问题，训练数据集怎么来获得的啊？有什么方法可以制作吗？如果有合成数据集的方法能分享一下吗？谢谢。。。。

**Comment by MaybeShewill-CV** [comment]
@huoguangdiandian 数据集用的是作者提供的数据集，根据论文我猜测制作数据集的方法是这样。首先固定相机，在没有下雨的情况下拍照，然后在不改变相机姿态的前提上在镜头前放一面沾了水的玻璃然后拍照，这样就形成了一组训练数据。至于雨点的大小就是你在玻璃上喷不同大小的水滴:)

**Comment by huoguangdiandian** [comment]
@MaybeShewill-CV 非常感谢，我还以为是作者合成的数据集

**Comment by MaybeShewill-CV** [comment]
@huoguangdiandian 不是合成的哈:)
