### ISSUE TITLE
Why did we choose VGG16 instead of other pretrained network?

### ISSUE THREAD

**Issue by zhaojianghe16** [MaybeShewill-CV/attentive-gan-derainnet#19]
Dear Friend,
     I was wondering if we could change VGG16  into other pre-trained networks like VGG19, ResNet50, Inception V3, Xception, Inception V4? 

Best,
Alan

**Comment by MaybeShewill-CV** [comment]
@zhaojianghe16 Yep you may change the backbone net:)

**Comment by zhaojianghe16** [comment]
@MaybeShewill-CV 
请问根据您的经验，更换成哪一个pre-trained会更有帮助去除雨滴呢？
又或者我应该根据什么指标去选择呢？
谢谢：）

**Comment by MaybeShewill-CV** [comment]
@zhaojianghe16 你可以查阅下使用perceptual loss的相关模型的backbone网络:)
