### ISSUE TITLE
How do we test the code?

### ISSUE THREAD

**Issue by zhaojianghe16** [MaybeShewill-CV/attentive-gan-derainnet#2]
Hi,
     I clone the code and put every  .py files in the same directory. When I use the pycharm python console:
 python tools/test_model.py --weights_path model/derain_gan_v2_2018-07-23-11-26-23.ckpt-200000
--image_path data/test_data/test_1.png

It returns python35 test_model.py --weights_path model/derain_gan_v2_2018-07-23-11-26-23.ckpt-200000 --image_path data/test_data/test_1.png
  File "<input>", line 1
    python35 test_model.py --weights_path model/derain_gan_v2_2018-07-23-11-26-23.ckpt-200000 --image_path data/test_data/test_1.png
                      ^
SyntaxError: invalid syntax.

When I directly run the test_model.py on pycharm, it returns D:\E\Anaconda3\envs\python35\python.exe D:/E/Deraincode/tools/test_model.py
Traceback (most recent call last):
  File "D:/E/Deraincode/tools/test_model.py", line 136, in <module>
    test_model(args.image_path, args.weights_path)
  File "D:/E/Deraincode/tools/test_model.py", line 64, in test_model
    assert ops.exists(image_path)
  File "D:\E\Anaconda3\envs\python35\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: can't specify None for path argument

Could you please provide a more detailed instruction about how to test the model after you clone the it from Github? Thank you so much

**Comment by MaybeShewill-CV** [comment]
If you want to test the model on windows machine you are supposed to adjust some file path

**Comment by zhaojianghe16** [comment]
@MaybeShewill-CV Thank you for your response. It will be super helpful if you could be more specific. I am using windows10. Please:)

**Comment by MaybeShewill-CV** [comment]
@zhaojianghe16 下载以后不要修改文件结构，直接按照readme文档中的例子来进行测试

**Comment by zhaojianghe16** [comment]
@MaybeShewill-CV  您好，我按照了readme测试。 但是会有ImportError: No module named 'attentive_gan_model'. 然后我一步一步的把按照把test model 和需要import 的文件移到了一起，解决的import error。但是当我用您的 python tools/test_model.py --weights_path model/derain_gan_v2_2018-07-23-11-26-23.ckpt-200000 --image_path data/test_data/test_1.png 不知道为什么总是会出现
Traceback (most recent call last):
  File "D:/E/GAN/attentive_gan_model/test_model.py", line 137, in <module>
    test_model(args.image_path, args.weights_path)
  File "D:/E/GAN/attentive_gan_model/test_model.py", line 64, in test_model
    assert ops.exists(image_path)
AssertionError

我已经把 data的文件夹移到了 和test_model.py train_model.py同一个目录了, D:\E\GAN\attentive_gan_model\data\test_data 也是有test_1.jpg 的. 请问这是什么原因呢？

**Comment by MaybeShewill-CV** [comment]
@zhaojianghe16 直接下载以后不需要更改文件结构 我代码写的import模块都是按照代码库的文件结构来写的

**Comment by MaybeShewill-CV** [comment]
Since there is no further response I will close it.
