### ISSUE TITLE
训练结果

### ISSUE THREAD

**Issue by Jiangzl** [MaybeShewill-CV/attentive-gan-derainnet#21]
你好，我下载了你的代码进行测试，但是由于无法加载模型，我重新对其进行了训练之后再测试，但是测试的结果非常爆炸，已经完全没有的原图的样子，我想请问一下你是否知道这是什么原因，使用python3.6,1080Ti。谢谢！（以下是使用test1.png实验的结果图，其他图片的测试结果也是这样）
![src_img](https://user-images.githubusercontent.com/8221918/50050601-e6989100-013a-11e9-8657-bc5f272a467e.png)
![derain_ret](https://user-images.githubusercontent.com/8221918/50050602-f31ce980-013a-11e9-8631-a84b604662cc.png)

**Comment by Jiangzl** [comment]
就是测试的时候显示找不到模型，就是无法正常加载，之后就根据给的数据集做了一个train.txt文件重新进行训练，并没有修改任何参数，直接训练的。
![screenshot from 2018-12-16 15-39-32](https://user-images.githubusercontent.com/8221918/50051210-13ec3b80-0149-11e9-8107-de2a4c87db41.png)这是训练的截图
![screenshot from 2018-12-16 15-40-17](https://user-images.githubusercontent.com/8221918/50051214-20709400-0149-11e9-973d-94767513d055.png)这是我的train.txt文件

**Comment by Jiangzl** [comment]
好的，请问训练日志的那个部分不正常显示训练失败呢？请问是Ssim值么？会不会是因为我的train.txt文件不对？

**Comment by MaybeShewill-CV** [comment]
@Jiangzl 嗯,这个SSIM值已经是负的了,肯定是训练失败了. 最近有点忙,有时间了我验证一下是不是修改了GN的缘故:)

**Comment by Jiangzl** [comment]
好的，谢谢楼主！如果有解了麻烦回复一下，万分感谢~

**Comment by Jiangzl** [comment]
作者你好，或者想请问一下你是否还保存有未修改之前的代码可以分享一下呢？谢谢~

**Comment by MaybeShewill-CV** [comment]
@Jiangzl 你可以git reset 回滚到原来的版本:)
