### ISSUE TITLE
Architecture   

### ISSUE THREAD

**Issue by zhaojianghe16** [MaybeShewill-CV/attentive-gan-derainnet#24]
您好，
     请问您的代码architecture和原paper 作者pytorch的 architecture是否完全一样呢？如果有修改，请问是哪些部分不同呢? 我用您的code在Research上有些进展。请问可以用您的code写paper吗？ 
     谢谢您~

**Comment by MaybeShewill-CV** [comment]
@zhaojianghe16 架构基本是一模一样的,只有一点微小的不一样.如果用到了我的代码,请cite我的repo就好:)

**Comment by zhaojianghe16** [comment]
@MaybeShewill-CV  谢谢您的秒回。 请问可以详细一点点告诉我哪些地方不同吗？ 这样可以避免我错误解读了您的代码。谢谢·：）·

**Comment by MaybeShewill-CV** [comment]
@zhaojianghe16 主要是加入一些normalization层,但是这个层的加入是否有正向收益,我现在还没有最终确认,因为对于图像恢复一类的任务普遍共识是normalization会影响最终的效果:)

**Comment by MaybeShewill-CV** [comment]
@zhaojianghe16 之前使用GN替换过BN层:)

**Comment by Carlyx** [comment]
> @zhaojianghe16 主要是加入一些normalization层,但是这个层的加入是否有正向收益,我现在还没有最终确认,因为对于图像恢复一类的任务普遍共识是normalization会影响最终的效果:)

您好，我目前在研究反射去除的图像恢复问题，其中同样涉及到了normalization层，我发现在conv和ReLU之间加入BN层会较明显的降低性能(batch_size=1)，所以目前都是不加入任何normalization层，请问应该怎么解释这个现象呢，主要原因是batch_size过小吗？ 凭借您的经验，如果加入GN层，是否会比不加任何归一化层效果更好？
