### ISSUE TITLE
How to Visualize attention map?

### ISSUE THREAD

**Issue by gimikk** [MaybeShewill-CV/attentive-gan-derainnet#25]
In your projects, there are some attention maps which are visualized probability model.
How to visualize attention model?
Is there any code in your project?

**Comment by MaybeShewill-CV** [comment]
@gimikk You may check this https://github.com/MaybeShewill-CV/attentive-gan-derainnet/blob/master/tools/test_model.py:)

**Comment by gimikk** [comment]
Thanks!
