### ISSUE TITLE
what is the diff between the mask and

### ISSUE THREAD

**Issue by laulampaul** [MaybeShewill-CV/attentive-gan-derainnet#26]

**Comment by laulampaul** [comment]
hello~ I read the code and I note how to generate the mask，but I want to ask why we need to generate the attention map ？Can we put the mask into the encodedecoder？thankyou~

**Comment by MaybeShewill-CV** [comment]
@laulampaul Attention map is used to let the net focus on the rain drop. You may read the origin paper for details:)
