### ISSUE TITLE
run test_model.py get errot

### ISSUE THREAD

**Issue by Magicyu-1990** [MaybeShewill-CV/attentive-gan-derainnet#28]
Hi! Thank you for providing Tensorflow code! When i git clone this repository, i got error by running test_model.py.

tensorflow.python.framework.errors_impl.NotFoundError: Key derain_net_loss/attentive_autoencoder_loss/autoencoder_inference/gn_1/beta not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key derain_net_loss/attentive_autoencoder_loss/autoencoder_inference/gn_1/beta not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Can you help to check this error?

**Comment by MaybeShewill-CV** [comment]
@Magicyu-1990 1.You can git reset to older version of the code 2.You may training your own model:)

**Comment by tuencfs** [comment]
Hi @Magicyu-1990  Did you resolve the issue?

**Comment by Magicyu-1990** [comment]
> Hi @Magicyu-1990 Did you resolve the issue?

I solve this issue by training from scratch.
