### ISSUE TITLE
分享训练结果

### ISSUE THREAD

**Issue by xiaopohai9570** [MaybeShewill-CV/attentive-gan-derainnet#30]

**Comment by MaybeShewill-CV** [comment]
@xiaopohai9570 You may git pull update the repo and test again:)

**Comment by xiaopohai9570** [comment]
> @ xiaopohai9570(@xiaopohai9570)你可以把更新的 Git 和测试再次回购:)感谢指导。我又遇到新的问题，就是tf继续训练，然后报错如图：
![2019-03-21 11-29-08 的屏幕截图](https://user-images.githubusercontent.com/34275468/54732090-d2967c80-4bcc-11e9-9635-9e09ce04a206.png) 
说我的checkpoint 无效，需要怎么修改一下？

**Comment by xiaopohai9570** [comment]
> @xiaopohai9570 You may git pull update the repo and test again:)

感谢您指导！但是我再训练的模型上继续训练，出现了如下错误：
![2019-03-21 11-29-08 的屏幕截图](https://user-images.githubusercontent.com/34275468/54732183-56e8ff80-4bcd-11e9-9537-aa2cdadcfe39.png)
请问这个怎么修改

**Comment by MaybeShewill-CV** [comment]
@xiaopohai9570 去查下tensorflow怎么从ckpt文件恢复模型

**Comment by xiaopohai9570** [comment]
谢谢作者回复。我现在的问题是，学习率您设置的是每10万步衰减0.1倍，但是我训练（30万次）发现为什么在18万次以后学习率就不变了，是太小了没法显示？如图：
![27](https://user-images.githubusercontent.com/34275468/55767400-53011c80-5aab-11e9-910a-c54c579a764c.jpg)
还有就是我的G_loss是收敛点，为什么我的d_loss从几十到几十万大小不等，请问这是怎么回事，该如何调整？如下图：
![48](https://user-images.githubusercontent.com/34275468/55767500-be4aee80-5aab-11e9-8be3-ab974f1534aa.jpg)

**Comment by MaybeShewill-CV** [comment]
@xiaopohai9570 1.训练完成后这个lr的曲线会正常显示 2.我也不知道

**Comment by xiaopohai9570** [comment]
![0](https://user-images.githubusercontent.com/34275468/56022320-f5383300-5d3d-11e9-8d1c-4b2bfc4ac2ae.jpg)
这地方的代码是不是上下写反了？

**Comment by MaybeShewill-CV** [comment]
@xiaopohai9570 应该是我写错了 周一改一下:)

**Comment by xiaopohai9570** [comment]
我想咨询您一个问题，您把tf训练好的模型，用Tensorflow.js做成了一个网页，我之前用的tf=1.10.不能做，运行脚本有错误。我想问您做的这个是tf=1.12下做的，请问只要安装完对应版本tf运行convert_tfjs_model.sh 脚本后，就能直接生成一个URL，还需要后台再做些什么不，我就是后面的过程有点不了解，求解答，谢谢！

**Comment by MaybeShewill-CV** [comment]
@xiaopohai9570 convert tfjs model只是生成了一个tensorflow js可以调用的模型,还需要自己进行网页相关的前端开发:)

**Comment by xiaopohai9570** [comment]
那我没有这方面的基础，就是说做一个这个麻烦不，您有时间指导一下吗

**Comment by MaybeShewill-CV** [comment]
@xiaopohai9570 做一个简单的网也不难的,TensorFlow js也有例子，自己可以去查阅一下:)

**Comment by xiaopohai9570** [comment]
好的！_diff_image = _diff_image.sum(axis=2)在mask_image这一块，这句代码是什么意思，为什么在width相加，我不知道为什么这么写

**Comment by MaybeShewill-CV** [comment]
@xiaopohai9570 axis=2不是axis=1

**Comment by xiaopohai9570** [comment]
那就是在C上加？可以通俗点解释一下吗，比如这样做是为了

**Comment by xiaopohai9570** [comment]
那就是在C上加？可以通俗点解释一下吗，比如这样做是为了

**Comment by MaybeShewill-CV** [comment]
@xiaopohai9570 可以看原文 有关mask生成的部分:)

**Comment by xiaopohai9570** [comment]
![QQ图片20190423214856](https://user-images.githubusercontent.com/34275468/56586185-cbbab980-6611-11e9-895f-96cc76120363.png)
我看了，但是不懂。。你解释一下这么做为了做什么呗，这地方确实不懂。。。。可怜

**Comment by xiaopohai9570** [comment]
我想问一下残差块源代码中的是3*3的卷积核，而 您用的是1*1的卷积核，请问这样做是效果好还是什么，希望解释一下。谢谢

**Comment by MaybeShewill-CV** [comment]
@xiaopohai9570 是我当时调参的时候调整了这个参数只有block最开始的conv的ksize为３.当时测试是这样的参数能得到比之前更好一点点的结果：）

**Comment by xiaopohai9570** [comment]
> @xiaopohai9570 是我当时调参的时候调整了这个参数只有block最开始的conv的ksize为３.当时测试是这样的参数能得到比之前更好一点点的结果：）
好的
