### ISSUE TITLE
SSIM基本不变，值为0.02

### ISSUE THREAD

**Issue by WilyZhao8** [MaybeShewill-CV/attentive-gan-derainnet#33]
你好，今天再用新程序训练时，SSIM的值一直在0.02左右，请问你遇到过类似的问题吗？

**Comment by MaybeShewill-CV** [comment]
@WilyZhao8 ssim和psnr计算有问题 下周有时间会修正过来 不过这个不影响网络正常训练:)

**Comment by MaybeShewill-CV** [comment]
@WilyZhao8 Problem has been fixed

**Comment by WilyZhao8** [comment]
Thank you very much！
