### ISSUE TITLE
网络训练输入尺寸

### ISSUE THREAD

**Issue by Penn000** [MaybeShewill-CV/attentive-gan-derainnet#36]
您好！请问训练时的输入如果不是256x376，除了`config/global_config.py`还需要修改哪些文件呢？还是说输入的训练必须是256x376的，否则reshape到该尺寸？谢谢！

**Comment by MaybeShewill-CV** [comment]
@Penn000 只需要修改global config文件 如果出现维度不匹配的情况你需要根据情况修改输入图像的维度:)

**Comment by Penn000** [comment]
> @Penn000 只需要修改global config文件 如果出现维度不匹配的情况你需要根据情况修改输入图像的维度:)

**Comment by Penn000** [comment]
谢谢您的回复:D
`global_config.py`里的`__C.TRAIN.IMG_HEIGHT`等参数在`train_model.py`, `derain_drop_net.py`等文件中都没有用到，貌似对训练并不产生影响。之前我先train了256x376的数据集，然后在原仓库中再train别的大小的数据集就出现了InvalidArgumentError，现在我把代码拷到别的地方就能train起来了，应该是某个我没发现的缓存文件导致的。谢谢您啦~
