### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './data/vgg16.npy'

### ISSUE THREAD

**Issue by anshulji** [MaybeShewill-CV/attentive-gan-derainnet#38]
I tried to train the model on my own data for first time and i got this filenotfound error in data/vgg16.npy
![err](https://user-images.githubusercontent.com/39632882/56434928-4aeb7d00-62f4-11e9-9dee-4f78bdc42b5b.png)

**Comment by MaybeShewill-CV** [comment]
@anshulji You need to download the file yourself and put it in ./data folder:)

**Comment by scangit** [comment]
Where can I download the file? I find  one through google, but i am not sure it is right or not?
