### ISSUE TITLE
测试结果

### ISSUE THREAD

**Issue by hemengzhe** [MaybeShewill-CV/attentive-gan-derainnet#39]
您好，我用原作者发布的测试集（test_a)，使用您发布的权重文件，只得到了26.38的PSNR,请问您有做过这个测试吗？

**Comment by MaybeShewill-CV** [comment]
@hemengzhe 之前测试过,具体数值我忘记了, 达不到原作者论文上写的评价指标.可能训练方法或者代码还是和原作者有差距，欢迎补充改进：）

**Comment by xiaopohai9570** [comment]
跟test_a中图的resize有很大的关系

**Comment by MaybeShewill-CV** [comment]
@xiaopohai9570 欢迎分享结果和经验:)
