### ISSUE TITLE
关于模型在测试集上测试的问题

### ISSUE THREAD

**Issue by duguangmeiyu** [MaybeShewill-CV/attentive-gan-derainnet#4]
您好！！！请问我用您的代码训练出来模型之后如何在测试集上进行测试呢？？

**Comment by zhaojianghe16** [comment]
@duguangmeiyu  您好~~!! 请问您按照readme可以成功进行测试吗？ 谢谢

**Comment by MaybeShewill-CV** [comment]
@zhaojianghe16 是测试有什么问题吗？

**Comment by zhaojianghe16** [comment]
@MaybeShewill-CV 您好，我直接clone了你的代码然后按照readme运行（没有做任何的改动）

D:\E\Anaconda3\envs\python35\python.exe D:/attentive-gan-derainnet-mastertrying/attentive-gan-derainnet-master/tools/test_model.py --weights_path model/derain_gan_v2_2018-07-23-11-26-23.ckpt-200000 --image_path data/test_data/test_1.png
Traceback (most recent call last):
  File "D:/attentive-gan-derainnet-mastertrying/attentive-gan-derainnet-master/tools/test_model.py", line 136, in <module>
    test_model(args.image_path, args.weights_path)
  File "D:/attentive-gan-derainnet-mastertrying/attentive-gan-derainnet-master/tools/test_model.py", line 64, in test_model
    assert ops.exists(image_path)
AssertionError

Process finished with exit code 1


我按照路径可以找到 derain_gan_v2_2018-07-23-11-26-23.ckpt-200000 和 test_1.png.
请问这个可能是我哪里做错了吗？
期待您的回复，谢谢！

**Comment by MaybeShewill-CV** [comment]
@zhaojianghe16 你可以在程序的根目录下运行这条命令或者直接使用绝对路径。因为你启动路径不对所以无法找到这个图像。

**Comment by MaybeShewill-CV** [comment]
@zhaojianghe16 好的 非常感谢 我现在改一下。能正常测试的话我就把这个issue关掉了哈。

**Comment by zhaojianghe16** [comment]
@MaybeShewill-CV  好的 谢谢~
