### ISSUE TITLE
运行test_model出现问题

### ISSUE THREAD

**Issue by Mifudi** [MaybeShewill-CV/attentive-gan-derainnet#40]
test setup failed
file F:\GAN_model\test_model.py, line 43
  def test_model(image_path, weights_path):
E       fixture 'image_path' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

大佬，求救

**Comment by MaybeShewill-CV** [comment]
@Mifudi 检查图像路径 然后仔细看readme吧:)
