### ISSUE TITLE
th

### ISSUE THREAD

**Issue by jilner** [MaybeShewill-CV/attentive-gan-derainnet#41]
thanks for your good job,  when I run the author's code which in pytorch, and out of memory in a 1080 gpu,but you can run in 1070gpu,what's the problem in pytorch,  and  the train image  is resized to hou much, will different train image  inifluence the reslut?
thanks

**Comment by MaybeShewill-CV** [comment]
@jilner I'm not familiar with pytorch. But the problem you meet may be caused by the image scale.You may read config/global_config.py file for hyperparameters that used in the model:)

**Comment by jilner** [comment]
thanks for reply,  what's the scale in your training?   if  I used image in small  scale, is it going to get worse in reslut?

**Comment by MaybeShewill-CV** [comment]
@jilner You may check this https://github.com/MaybeShewill-CV/attentive-gan-derainnet/blob/master/config/global_config.py for image size:)

**Comment by jilner** [comment]
thanks
