### ISSUE TITLE
train with gpu

### ISSUE THREAD

**Issue by swordzxz** [MaybeShewill-CV/attentive-gan-derainnet#44]
hello；
Which parameters should I modify so that training can be done under the gpu?
look forward to your reply
thank you very much

**Comment by MaybeShewill-CV** [comment]
@swordzxz If your training process was not excepted under GPU please check if your Tensorflow or your CUDA is correctly installed:)

**Comment by swordzxz** [comment]
thank you for your reply
I  install the tensorflow gpu, the program can train with gpu
