### ISSUE TITLE
my test data is not well,i don't know reason

### ISSUE THREAD

**Issue by hanrui15765510320** [MaybeShewill-CV/attentive-gan-derainnet#46]
hello, I use your weight to test my picture ,but results is not well,in fact ,there is no differents about my picture and results.I have no ideals about that,so please help me
![15ab89182fd360bc271cca1551ed386](https://user-images.githubusercontent.com/48637150/60152460-2c819080-9813-11e9-8d91-f6a60ff05f76.jpg)

**Comment by MaybeShewill-CV** [comment]
@hanrui15765510320 You need your own dataset to finetune the pretrained model:)
