### ISSUE TITLE
cudnn

### ISSUE THREAD

**Issue by chenhuiphd** [MaybeShewill-CV/attentive-gan-derainnet#49]
UnknownError (see above for traceback): Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	hi，cuda-9.0, cudnn-7.0 ， i cannot run this code ，why？

**Comment by MaybeShewill-CV** [comment]
@chenhuiphd Most likely you have wrongly installed cuda and cudnn:)
