### ISSUE TITLE
How to achieve a better result of deraining?

### ISSUE THREAD

**Issue by zhaojianghe16** [MaybeShewill-CV/attentive-gan-derainnet#5]
Dear Friend,
     I ran the test_model.py with the test_1.jpg, test_2.png and test_3.png (directory: \attentive-gan-derainnet-master\data\test_data). However, it seemed the model could not get rid of the raindrops as well as the photo pairs(with raindrops, and after deraining) illustrated in the readme. May I ask what is your future plan? Or could you give me some instructions for continuing to train the model? 
     I am very curious about your answer. Thank you so much!

**Comment by MaybeShewill-CV** [comment]
@zhaojianghe16 You may not pull the newest code. The test data now is test_1.png, test_2.png and test_3.png. You may test them.

**Comment by MaybeShewill-CV** [comment]
@zhaojianghe16 You can also test the model on the origin dataset supplied by the origin author

**Comment by zhaojianghe16** [comment]
Hi. Thank you for your quick response. 
 Did you mean "You may **now** pull the newest code."  instead of "**not**"?  I am not sure what you meant. Thanks.

**Comment by MaybeShewill-CV** [comment]
@zhaojianghe16 Yep you can update the repo and test the model on the data/test_data/*.png. If there is something wrong you can put the result here:)
