### ISSUE TITLE
dataset size

### ISSUE THREAD

**Issue by swordzxz** [MaybeShewill-CV/attentive-gan-derainnet#53]

**Comment by swordzxz** [comment]
hi，
When I want to change the size of the image 352*512 to 270*360 in config and retrain, I have encountered such a problem.

![image](https://user-images.githubusercontent.com/45188129/63438325-ae321b00-c45e-11e9-98a2-eba8de86248a.png)

![image](https://user-images.githubusercontent.com/45188129/63438388-cbff8000-c45e-11e9-97d7-da0b79f88e94.png)

![image](https://user-images.githubusercontent.com/45188129/63438416-d6ba1500-c45e-11e9-8782-5e4c7164c4f2.png)

How should I solve it?
Looking forward to your reply

Thank you

**Comment by MaybeShewill-CV** [comment]
@swordzxz you need to checkout your dataset's input image shape:)
