### ISSUE TITLE
关于使用自己图片测试的问题.

### ISSUE THREAD

**Issue by texasmotorcycle** [MaybeShewill-CV/attentive-gan-derainnet#54]
你好,我在电脑上使用预训练好的模型复现了程序对测试图片进行了去雨,但是当我下载了一些自己有雨滴的图片进行测试时结果没有实现去雨效果.
我已经改为了png格式,大小也设置为了720*480,但不管用.
想请教一下如何设置可以测试自己的图片,谢谢.

**Comment by MaybeShewill-CV** [comment]
@texasmotorcycle 我这边复现的模型本身泛化能力就不是那么强 我试原作者提供的模型也是这样 自己的一些测试数据无法有效去除。毕竟作者使用的训练数据集量就不是很大，所以也可以理解：）

**Comment by texasmotorcycle** [comment]
知道了，十分感谢。那您有没有了解一些图像去雨或者去噪的开源算法可以推荐一下，我这边想了解一下图像预处理的去噪，但文献很多，开源的代码却很少。




------------------ 原始邮件 ------------------
发件人: "MaybeShewill-CV"<notifications@github.com>;
发送时间: 2019年8月29日(星期四) 上午10:39
收件人: "MaybeShewill-CV/attentive-gan-derainnet"<attentive-gan-derainnet@noreply.github.com>;
抄送: "LQ、"<1398385429@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [MaybeShewill-CV/attentive-gan-derainnet] 关于使用自己图片测试的问题. (#54)




@texasmotorcycle 我这边复现的模型本身泛化能力就不是那么强 我试原作者提供的模型也是这样 自己的一些测试数据无法有效去除。毕竟作者使用的训练数据集量就不是很大，所以也可以理解：）

**Comment by MaybeShewill-CV** [comment]
@texasmotorcycle 这个你可以搜搜最近的cvpr和iccv:)
