### ISSUE TITLE
image size

### ISSUE THREAD

**Issue by chenhuiphd** [MaybeShewill-CV/attentive-gan-derainnet#55]
hi，Why are the test pictures the same size as the training pictures?, otherwise otherwise the program will make mistakes in the test? thx
![a1626f1fc8e80add033eb6f5ca87717](https://user-images.githubusercontent.com/42506206/64077129-d263e680-ccff-11e9-819c-80c4300fcbb9.png)

**Comment by MaybeShewill-CV** [comment]
@chenhuiphd That problem was caused by the mismatched compute graph and restored weights file in my opinion:)
