### ISSUE TITLE
High Resolution image

### ISSUE THREAD

**Issue by OliverTeo288** [MaybeShewill-CV/attentive-gan-derainnet#62]
Hi I have a high resolution image that needs to be derain through your model. How would you suggest i go about doing it? The resolution of my test image is 1920 x 1080. Thanks in advance

**Comment by MaybeShewill-CV** [comment]
@OliverTeo288 1. rescale the image 2. split the image into patches:)

**Comment by OliverTeo288** [comment]
I have tried resizing the image but alot of information of the image have been lost after the resize. Which the image becomes distorted. After applying filters to the distorted images the derain results are not very good.

**Comment by MaybeShewill-CV** [comment]
@OliverTeo288 If you want a better result you may retrain a new model on your own dataset:)

**Comment by OliverTeo288** [comment]
@MaybeShewill-CV alright thanks for your help. You are amazing ! All the best :)
