### ISSUE TITLE
rain can not be removed in centos

### ISSUE THREAD

**Issue by kaixinwangzi1982** [MaybeShewill-CV/attentive-gan-derainnet#63]
In aliyun Centos 7, there is no GPU, only gpu. I used the model "derain_gan_2018-11-02-19-55-27.ckpt-200000" and the rain can not be removed.  It works in Macbook used the same model

**Comment by MaybeShewill-CV** [comment]
@kaixinwangzi1982 That's maybe a problem relative to tensorflow rather than the model itself:)
