### ISSUE TITLE
error

### ISSUE THREAD

**Issue by cmqAccount** [MaybeShewill-CV/attentive-gan-derainnet#64]
您好，我跑您的代码的时候，出现这样的一个问题，请问是什么原因呢
NotFoundError (see above for traceback): Key derain_net/attentive_rnn_loss/attentive_inference/residual_block_4/block_5_conv_2/W not found in checkpoint
	 [[Node: save/RestoreV2_125 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"]

**Comment by MaybeShewill-CV** [comment]
@cmqAccount 代码和模型不匹配 仔细看看readme文件吧
