### ISSUE TITLE
test报错

### ISSUE THREAD

**Issue by Dominic-ZZ** [MaybeShewill-CV/attentive-gan-derainnet#66]
Not found: Key derain_net/attentive_rnn_loss/attentive_inference/residual_block_1/block_0_conv_1/b not found in checkpoint
请问是哪里的问题

**Comment by MaybeShewill-CV** [comment]
@Dominic-ZZ 下载的模型文件不对 你看看是不是在最新的链接下下载的：）

**Comment by 41meliodas** [comment]
> @Dominic-ZZ 下载的模型文件不对 你看看是不是在最新的链接下下载的：）

作者你好，我也是一样的报错。
Not found: Key derain_net/attentive_rnn_loss/attentive_inference/residual_block_1/block_0_conv_1/b not found in checkpoint

**Comment by MaybeShewill-CV** [comment]
@41meliodas 模型在哪里下载的， 贴一下原始链接在文档里的位置:)

**Comment by 41meliodas** [comment]
> @41meliodas 模型在哪里下载的， 贴一下原始链接在文档里的位置:)

https://github.com/MaybeShewill-CV/attentive-gan-derainnet/tree/master/model
就是这个里面的

**Comment by MaybeShewill-CV** [comment]
@41meliodas 嗯 应该是我代码改了但是模型没有同步上传 我找一下还在不在 然后重新上传下吧:)

**Comment by 41meliodas** [comment]
> @41meliodas 嗯 应该是我代码改了但是模型没有同步上传 我找一下还在不在 然后重新上传下吧:)

感谢感谢

**Comment by MaybeShewill-CV** [comment]
@41meliodas 重新上传了下 可以再试试:)
