### ISSUE TITLE
train model的时候报错

### ISSUE THREAD

**Issue by MoyangSensei** [MaybeShewill-CV/attentive-gan-derainnet#67]
提示说是少了文件  路径是./data/vgg16.npy

<img width="667" alt="屏幕快照 2020-04-29 16 22 53" src="https://user-images.githubusercontent.com/48516430/80575219-c74f8a80-8a35-11ea-92ff-537be96beae7.png">

想问一下是不是我这边少下载了什么东西（更新过的文件我都有更新），还是这个文件是在运行过程中生成的（我搜索了这个文件，也没发现还有别的地方提到有生成这个文件）。初学者，代码看的不是太懂。麻烦了。

**Comment by MaybeShewill-CV** [comment]
@MoyangSensei 缺少文件 搜索下载一下然后放到指定位置:)

**Comment by MoyangSensei** [comment]
> @MoyangSensei 缺少文件 搜索下载一下然后放到指定位置:)

明白了，这原来是个大众的文件。我还以为是这中间生成了什么东西。谢谢。

**Comment by MaybeShewill-CV** [comment]
@MoyangSensei 没事儿:)
