### ISSUE TITLE
test_model.py中的label_path

### ISSUE THREAD

**Issue by MoyangSensei** [MaybeShewill-CV/attentive-gan-derainnet#69]
命令中只给了前两个参数，就是weightpath和imagepath，label_path默认的是None。

我想测试我自己跑出来的模型，结果什么都没输出，不管是两个参数还是图像。我发现test_model中有两个判断label_path是否存在的if语句，我在前后做了print的测试，发现这些代码实际上没运行，就是因为这个label_path。

label_path到底是什么，该如何解决不输出结果的问题。谢谢。

**Comment by MoyangSensei** [comment]
我自己填入了label_path，填的是对应的clean的图片。可以运行出结果，但是又出来一个问题就是derain_ret这张图片是没有结果的，就像下面这样。

<img width="562" alt="屏幕快照 2020-05-04 17 32 37" src="https://user-images.githubusercontent.com/48516430/80953036-52ad8f00-8e2d-11ea-8675-cb92ecc8a785.png">

这又是为什么呢，是不是我的网络训练有问题或者私自填的命令行参数有问题。四张attemap图片是没有问题的。

**Comment by MaybeShewill-CV** [comment]
@MoyangSensei 贴一下你的命令行吧

**Comment by MoyangSensei** [comment]
1、原本的命令：
python3 tools/test_model.py --weights_path model/derain_gan/derain_gan_2020-05-02-02-49-36.ckpt-20000 --image_path test_a/data/9_rain.png
这条命令什么结果也不输出

2、加了--label_path的命令：
python3 tools/test_model.py --weights_path model/derain_gan/derain_gan_2020-05-02-02-49-36.ckpt-20000 --image_path test_a/data/9_rain.png --label_path test_a/gt/9_clean.png
这条命令可以正常输出两个参数的结果和6张图，输出的原图和4张attmap没问题，derain的图就像上面那样

**Comment by MoyangSensei** [comment]
1、原本的命令：
python3 tools/test_model.py --weights_path model/derain_gan/derain_gan_2020-05-02-02-49-36.ckpt-20000 --image_path test_a/data/9_rain.png
这条命令什么结果也不输出

2、加了--label_path的命令：
python3 tools/test_model.py --weights_path model/derain_gan/derain_gan_2020-05-02-02-49-36.ckpt-20000 --image_path test_a/data/9_rain.png --label_path test_a/gt/9_clean.png
这条命令可以正常输出两个参数的结果和6张图，输出的原图和4张attmap没问题，derain的图就像上面那样

> @MoyangSensei 贴一下你的命令行吧

**Comment by MaybeShewill-CV** [comment]
@MoyangSensei 我在本地测试了 没有问题呀
![Screenshot from 2020-05-06 13-56-00](https://user-images.githubusercontent.com/15725187/81142167-7396f100-8fa1-11ea-87e3-757147943e77.png)

不知道你对测试脚本是不是有什么修改 或者你读入的图像有问题:)

**Comment by MoyangSensei** [comment]
> @MoyangSensei 我在本地测试了 没有问题呀
> ![Screenshot from 2020-05-06 13-56-00](https://user-images.githubusercontent.com/15725187/81142167-7396f100-8fa1-11ea-87e3-757147943e77.png)
> 
> 不知道你对测试脚本是不是有什么修改 或者你读入的图像有问题:)

我看到你的命令行里把gpu屏蔽了,我也尝试着这样做了一下，发现可以正常的输出去雨图片的结果了。不过需要输出两个指标的话还是需要带上label_path。

谢谢！

**Comment by MaybeShewill-CV** [comment]
@MoyangSensei 屏蔽gpu是因为我的gpu正在干别的 你不屏蔽gpu也是没问题的。 如果你需要计算ssim和psnr的话是必须要label的 否则无法计算:)

**Comment by MoyangSensei** [comment]
> @MoyangSensei 屏蔽gpu是因为我的gpu正在干别的 你不屏蔽gpu也是没问题的。 如果你需要计算ssim和psnr的话是必须要label的 否则无法计算:)

我这边四张卡都可用，但是如果不屏蔽GPU的话就无法得到去雨图片。我也不知道这是为什么。不过结果能正常输出就行。

谢谢。

**Comment by MaybeShewill-CV** [comment]
@MoyangSensei ok:)
