### ISSUE TITLE
batch size

### ISSUE THREAD

**Issue by Carlyx** [MaybeShewill-CV/attentive-gan-derainnet#73]
您好，我看到一些inpainting的项目，如反射去除，去雨滴等问题都因batchsize较小而不加BN层。
请问一下这类问题为什么不把batchsize变大并且加上BN层呢，会出现什么样消极的影响嘛？
@MaybeShewill-CV

**Comment by MaybeShewill-CV** [comment]
@Carlyx 从之前的实验结果上看容易在图像边缘的地方出现小的模糊斑:)

**Comment by Carlyx** [comment]
好的，明白啦，感谢您的耐心解答。
