### ISSUE TITLE
the bug

### ISSUE THREAD

**Issue by crazygirl1992** [MaybeShewill-CV/attentive-gan-derainnet#76]
hellow,i can run the test code,but,when i run the train code,this bug happened, why this happened?

tensorflow.python.framework.errors_impl.InvalidArgumentError:  Input to reshape is a tensor with 288768 values, but the requested shape has 786432
	 [[val_IteratorGetNext]]

**Comment by MaybeShewill-CV** [comment]
@crazygirl1992 You must have used images with wrong image shape. Generate tfrecords first and then do the training procedure

**Comment by crazygirl1992** [comment]
thank you, i have resolved this problem,and why i run the code,it use cpu nor GPU,i have the same arg setting

**Comment by MaybeShewill-CV** [comment]
@crazygirl1992 You must installed tensorflow gpu incorrectly. That's a environment relative problem and there should be nothing wrong with this code repo:)
