### ISSUE TITLE
Colab Test

### ISSUE THREAD

**Issue by arteezyela** [MaybeShewill-CV/attentive-gan-derainnet#79]
![image](https://user-images.githubusercontent.com/85997781/122210968-6d778180-ced0-11eb-84ee-8a35d2f43c44.png)

Can you help me with this ? i run that code on collab

and I wanna try to run this test code on my pc (without colab)
what things should i install ?

thank you

**Comment by MaybeShewill-CV** [comment]
@arteezyela Not familiar with colab but if you want to test it on your own pc without colab the README file will guide you.

**Comment by xuchen-dev** [comment]
可以分享一下数据集嘛 不翻墙好像下不了  有百度云链接吗  或者可以发我邮箱947628380@qq.com  

有没有什么检测雨点 的模型 或者论文推荐了   如果能够回复，将非常感谢
