### ISSUE TITLE
@MMaybeShewill-CV ,It really makes me wonder that the attentive attentive-recurrent network can get the raindrop attention ,not the background g attention features?

### ISSUE THREAD

**Issue by 675492062** [MaybeShewill-CV/attentive-gan-derainnet#8]
@MMaybeShewill-CV ,It really makes me wonder that the  attentive-recurrent network can get the raindrop attention ,not the background  attention features?

**Comment by MaybeShewill-CV** [comment]
@675492062 You're welcome
