### ISSUE TITLE
no file named "./data/vgg16.npy"

### ISSUE THREAD

**Issue by Jamofl** [MaybeShewill-CV/attentive-gan-derainnet#85]
hello, when i run the train_model.py, there was an errer:
in file train_model.py , line 262 :  no such file or directory "./data/vgg16.npy"

and when i dive into ./data, there is  actually no such file("vgg16.npy") here!

looking forward to your response. thanks a lot!

**Comment by Jamofl** [comment]
can you provide the vgg.16.npy file to me ?  or is there something else wrong...

**Comment by MaybeShewill-CV** [comment]
@Jamofl You may search the file through Google:)

**Comment by Jamofl** [comment]
solved! thanks a lot!
