### ISSUE TITLE
训练时Discriminator的loss不收敛问题

### ISSUE THREAD

**Issue by Jamofl** [MaybeShewill-CV/attentive-gan-derainnet#87]
您好！ 非常感谢您的代码！
我在使用其他雨滴数据集进行训练时遇到了这样的情况：在大约训练到第14000 epoch时，鉴别器的loss从0升到15左右，然后一直维持在这个水平，直到10w  epoch训练结束，请问这是怎么回事呀？  

请问改变数据集的话，还需要改变哪些参数吗？期待您的回复！ 非常感谢！
Epoch_Train: 14181 D_loss: 0.00622 G_loss: 0.99063 SSIM: 0.92173 PSNR: 29.37859 Cost_time: 0.45720s
Epoch_Train: 14182 D_loss: 0.01008 G_loss: 0.70841 SSIM: 0.95254 PSNR: 28.91425 Cost_time: 0.45934s
Epoch_Train: 14183 D_loss: 0.01015 G_loss: 1.71491 SSIM: 0.89044 PSNR: 26.75873 Cost_time: 0.46000s
Epoch_Train: 14184 D_loss: 0.00459 G_loss: 0.94037 SSIM: 0.92423 PSNR: 29.48820 Cost_time: 0.45957s
Epoch_Train: 14185 D_loss: 0.00478 G_loss: 1.09866 SSIM: 0.92443 PSNR: 28.99318 Cost_time: 0.46253s
Epoch_Train: 14186 D_loss: 0.00575 G_loss: 0.72388 SSIM: 0.93164 PSNR: 30.95709 Cost_time: 0.46485s
Epoch_Train: 14187 D_loss: 0.06432 G_loss: 0.63994 SSIM: 0.93900 PSNR: 30.13286 Cost_time: 0.45792s
Epoch_Train: 14188 D_loss: 0.00735 G_loss: 0.95833 SSIM: 0.84905 PSNR: 26.23130 Cost_time: 0.46051s
Epoch_Train: 14189 D_loss: 0.00322 G_loss: 1.51706 SSIM: 0.84874 PSNR: 27.94430 Cost_time: 0.46038s
Epoch_Train: 14190 D_loss: 0.01093 G_loss: 1.13478 SSIM: 0.89547 PSNR: 27.60135 Cost_time: 0.46360s
Epoch_Train: 14191 D_loss: 0.00339 G_loss: 0.86030 SSIM: 0.90930 PSNR: 29.44472 Cost_time: 0.46059s
Epoch_Train: 14192 D_loss: 14.01000 G_loss: 1.07465 SSIM: 0.91109 PSNR: 27.46113 Cost_time: 0.46234s
Epoch_Train: 14193 D_loss: 0.00592 G_loss: 1.49669 SSIM: 0.90190 PSNR: 25.11241 Cost_time: 0.46117s
Epoch_Train: 14194 D_loss: 0.00399 G_loss: 0.96835 SSIM: 0.92080 PSNR: 27.84681 Cost_time: 0.46161s
Epoch_Train: 14195 D_loss: 0.00404 G_loss: 1.32799 SSIM: 0.87797 PSNR: 26.07203 Cost_time: 0.45559s
Epoch_Train: 14196 D_loss: 0.00305 G_loss: 0.82456 SSIM: 0.91988 PSNR: 27.09984 Cost_time: 0.46356s
Epoch_Train: 14197 D_loss: 0.00698 G_loss: 1.65623 SSIM: 0.89104 PSNR: 25.90995 Cost_time: 0.45888s
Epoch_Train: 14198 D_loss: 0.00460 G_loss: 0.77525 SSIM: 0.89918 PSNR: 32.11379 Cost_time: 0.45696s
Epoch_Train: 14199 D_loss: 0.01136 G_loss: 1.11077 SSIM: 0.88222 PSNR: 25.30873 Cost_time: 0.45991s
Epoch_Train: 14200 D_loss: 0.02190 G_loss: 1.98785 SSIM: 0.85421 PSNR: 25.41487 Cost_time: 0.45940s
Epoch_Train: 14201 D_loss: 0.00956 G_loss: 0.63746 SSIM: 0.92519 PSNR: 29.54581 Cost_time: 0.45877s
Epoch_Train: 14202 D_loss: 0.00687 G_loss: 0.65243 SSIM: 0.94071 PSNR: 24.52595 Cost_time: 0.46072s
Epoch_Train: 14203 D_loss: 0.02996 G_loss: 1.20789 SSIM: 0.89758 PSNR: 26.43548 Cost_time: 0.45810s
Epoch_Train: 14204 D_loss: 13.82231 G_loss: 0.86050 SSIM: 0.94726 PSNR: 29.35911 Cost_time: 0.46333s
Epoch_Train: 14205 D_loss: 0.02982 G_loss: 0.67258 SSIM: 0.93838 PSNR: 30.06240 Cost_time: 0.46312s
Epoch_Train: 14206 D_loss: 0.07316 G_loss: 1.28689 SSIM: 0.92189 PSNR: 27.16131 Cost_time: 0.45833s
Epoch_Train: 14207 D_loss: 16.06720 G_loss: 1.73016 SSIM: 0.86451 PSNR: 26.46809 Cost_time: 0.45676s
Epoch_Train: 14208 D_loss: 16.23168 G_loss: 0.75785 SSIM: 0.92729 PSNR: 27.10830 Cost_time: 0.45827s
Epoch_Train: 14209 D_loss: 16.16609 G_loss: 0.73237 SSIM: 0.93642 PSNR: 26.03369 Cost_time: 0.46219s
Epoch_Train: 14210 D_loss: 16.84928 G_loss: 0.84836 SSIM: 0.93906 PSNR: 27.80629 Cost_time: 0.45689s
Epoch_Train: 14211 D_loss: 16.65714 G_loss: 0.21077 SSIM: 0.95854 PSNR: 33.55317 Cost_time: 0.45587s
Epoch_Train: 14212 D_loss: 17.08031 G_loss: 0.72672 SSIM: 0.92749 PSNR: 29.69357 Cost_time: 0.46303s
Epoch_Train: 14213 D_loss: 16.75801 G_loss: 0.74262 SSIM: 0.94898 PSNR: 26.82167 Cost_time: 0.45507s
Epoch_Train: 14214 D_loss: 17.19547 G_loss: 0.77876 SSIM: 0.94408 PSNR: 28.99708 Cost_time: 0.45813s
Epoch_Train: 14215 D_loss: 16.74506 G_loss: 0.49924 SSIM: 0.92560 PSNR: 33.01609 Cost_time: 0.45798s
![image](https://user-images.githubusercontent.com/33048872/142620047-a810c97c-5370-40db-afac-7b1fe69366b7.png)

**Comment by MaybeShewill-CV** [comment]
@Jamofl 我还没有在别的数据集上测试过。可以先尝试减小学习率试试。不过看这个ssim和psnr应该还算不低了：）可以贴下效果图看下

**Comment by Jamofl** [comment]
好的，非常感谢。还有个小问题想请教下：原论文中的这种gan应该是属于监督学习范畴吧？ 因为包含有雨图像和无雨图像对，是属于有标签的。

**Comment by MaybeShewill-CV** [comment]
@Jamofl 嗯

**Comment by alan0324** [comment]
@Jamofl 您好，我在訓練時在loss那一部分遇到了一點問題，想請教您是否有遇過lm_loss和mse_loss張量不合的問題呢 謝謝!
