### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Kamalhsn** [MaybeShewill-CV/attentive-gan-derainnet#88]
Hi, Your work is so impressive. At present, I am working on a real dataset where I have to remove raindrops. I found that you prepared a mask image with _diff_image >= 35 (Ref: attentive-gan-derainnet/data_provider/tf_io_pipline_tools.py/line-92). However, I am not getting why did you do that particularly. Can I get more information about this mask image preparation?
Thanks in advance.

**Comment by MaybeShewill-CV** [comment]
@Kamalhsn That's a threshold which you may adjust to suit your local dataset:)

**Comment by Kamalhsn** [comment]
OK. Can you please provide the criteria to choose the threshold value to extract all the raindrops? 
I mean, any resources?

**Comment by Kamalhsn** [comment]
Hi, How did you choose number of iterations to generate attention maps and didn't you include the attention loss in the model training?

**Comment by Jack-Crum** [comment]
I don't have the file in the path of ./data/vgg16.npy
Therefore, I have no idea to run your train_model.py
Can anyone help to upload that file? Thank you a lot!
My eami address is 2629946925@qq.com

**Comment by Jack-Crum** [comment]
> 

Can you help me to upload the vgg16.npy file? Thank you a lot!

**Comment by MaybeShewill-CV** [comment]
@Jack-Crum 随便百度一下就有了啊==！ https://blog.csdn.net/lqp888888/article/details/80699125

**Comment by MaybeShewill-CV** [comment]
@Kamalhsn parameters were based on the origin paper. You may find the details from the origin paper:)
