### ISSUE TITLE
Outstanding work

### ISSUE THREAD

**Issue by shz1314** [MaybeShewill-CV/attentive-gan-derainnet#9]
Hi
  The original author didnt publish the training code. Therefore very thanks for your work. Have you reproduce the result which is in the paper?

**Comment by MaybeShewill-CV** [comment]
@shz1314 It seems that the derain result is almost the same as the origin paper work. But I have not calculated the quantitative evaluation results on the whole dataset. I will calculate them and compare to the origin paper. You may test the model your self and see if you are satisfied with the model's performance. Thanks:)
