### ISSUE TITLE
测试的问题

### ISSUE THREAD

**Issue by changruowang** [MaybeShewill-CV/attentive-gan-derainnet#94]
请问我在自己电脑上运行测试的时候在 saver.restore(sess, tf.train.latest_checkpoint(weights_path)) 函数会消耗很多时间
并且推理去雨后的图像全黑

**Comment by MaybeShewill-CV** [comment]
@changruowang restore是在加载模型比较耗时。推理后的图像全黑应该是输入数据的问题，没有更多信息目前无法定位:)
